### ISSUE TITLE
`not` got compiled to `not_`

### ISSUE THREAD

**Issue by banacorn** [Risto-Stevcev/bs-chai#3]
`BsChai.Expect.Modifiers.not` got incorrectly compiled to `not_` somehow by BuckleScript (using `bs-platform-5.0.4`)

**Comment by Risto-Stevcev** [comment]
It's intentional because `not` is a keyword in javascript so it can't be used as an identitier. Closing this as it's bucklescript-specific behavior.

**Comment by banacorn** [comment]
BuckleScript now gives warning if the name of the binding target is omitted:

```
[@bs.get] external not: chai => chai = "";
```

Telling BuckleScript to transpile it as `"not"` will do:

```
[@bs.get] external not: chai => chai = "not";
```

**Comment by Risto-Stevcev** [comment]
Ah I see what you mean, I rushed through reading this and didn't notice, sorry about that. Yeah `not` isn't a reserved keyword in Javascript or Ocaml so this shouldn't be happening. I'll push up a fix for this

**Comment by Risto-Stevcev** [comment]
Ok I updated the `external` and bumped the version. Let me know if it's working for you now and I'll close the ticket

**Comment by banacorn** [comment]
Thank you, it's working for me. I'll close the ticket then!
